import { auth, db } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, doc, getDoc, getDocs, setDoc, updateDoc, addDoc, query, orderBy, limit, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const $=id=>document.getElementById(id); const page=location.pathname.toLowerCase(); const isHome=page.endsWith('/')||page.endsWith('index.html'); const isStudent=page.endsWith('student.html');
const state={profile:null,courses:[],lessons:[],tests:[],results:[],announcements:[],currentCourse:null};
const fallbackCourses=[
 {id:'sample-math',title:'Matematik | Temel Konular',icon:'∑',color:'gold',description:'Sayılar, işlemler, kesirler ve problem çözmenin temelleri.',featured:true,sample:true,lessons:[['Sayılar ve Basamaklar','Doğal sayıları tanı, basamak değerini öğren.'],['Dört İşlem','Toplama, çıkarma, çarpma ve bölme stratejileri.'],['Kesirler','Kesri anla, karşılaştır ve işlemlerini öğren.']]},
 {id:'sample-turkish',title:'Türkçe | Anlama ve Paragraf',icon:'A',color:'rose',description:'Okuduğunu anlama, paragraf ve dil bilgisi çalışmaları.',featured:true,sample:true,lessons:[['Sözcükte Anlam','Eş anlam, zıt anlam ve sözcük ilişkileri.'],['Cümlede Anlam','Cümlelerin taşıdığı anlamı çözümle.'],['Paragraf','Ana fikir, yardımcı fikir ve çıkarım.']]},
 {id:'sample-science',title:'Fen Bilimleri | Bilim Dünyası',icon:'⚗',color:'blue',description:'Madde, enerji, canlılar ve dünya hakkında temel bilgiler.',featured:true,sample:true,lessons:[['Madde ve Özellikleri','Maddenin halleri ve ayırt edici özellikleri.'],['Kuvvet ve Hareket','Kuvvetin hareket üzerindeki etkileri.'],['Dünya ve Evren','Dünya, Güneş ve Ay arasındaki ilişki.']]},
 {id:'sample-social',title:'Sosyal Bilgiler | Geçmişten Geleceğe',icon:'◎',color:'violet',description:'Tarih, coğrafya, vatandaşlık ve kültür içerikleri.',featured:false,sample:true,lessons:[['Zaman İçinde Bilim','Bilim tarihinden önemli gelişmeler.'],['Haritalar','Yönler, ölçek ve harita okuma.'],['Toplum ve Kültür','Toplumsal yaşam ve kültürel miras.']]},
 {id:'sample-english',title:'English | Starter',icon:'EN',color:'green',description:'Temel kelimeler, günlük ifadeler ve cümleler.',featured:false,sample:true,lessons:[['Greetings','Hello, goodbye ve tanışma ifadeleri.'],['Daily Life','Günlük yaşam kelimeleri.'],['Simple Sentences','Temel cümle yapıları.']]}
];

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function hide(e){e?.classList.add('hidden')} function show(e){e?.classList.remove('hidden')}
function toast(m){const t=$('toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2600)}
function ferr(e){const m={'auth/invalid-credential':'E-posta veya şifre yanlış.','auth/email-already-in-use':'Bu e-posta zaten kayıtlı.','auth/weak-password':'Şifre en az 6 karakter olmalı.','auth/invalid-email':'Geçerli bir e-posta gir.','auth/network-request-failed':'İnternet bağlantısını kontrol et.'};return m[e.code]||'Bir hata oluştu.'}

if(isHome && $('loginForm')){
 $('loginTab').onclick=()=>{ $('loginTab').classList.add('active');$('registerTab').classList.remove('active');show($('loginForm'));hide($('registerForm'));$('authTitle').textContent='Tekrar hoş geldin.';$('authDesc').textContent='Beray hesabınla devam et.'; };
 $('registerTab').onclick=()=>{ $('registerTab').classList.add('active');$('loginTab').classList.remove('active');hide($('loginForm'));show($('registerForm'));$('authTitle').textContent='Beray ailesine katıl.';$('authDesc').textContent='Öğrenci hesabını birkaç saniyede oluştur.'; };
 $('showLoginPassword').onclick=()=>toggleType('loginPassword','showLoginPassword'); $('showRegisterPassword').onclick=()=>toggleType('registerPassword','showRegisterPassword');
 $('loginForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='';try{await signInWithEmailAndPassword(auth,$('loginEmail').value.trim().toLowerCase(),$('loginPassword').value)}catch(err){$('authMessage').textContent=ferr(err)}};
 $('registerForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='';const name=$('registerName').value.trim(),email=$('registerEmail').value.trim().toLowerCase(),pass=$('registerPassword').value;if(!name)return;$('registerButton')?.setAttribute('disabled','true');try{const c=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,'users',c.user.uid),{uid:c.user.uid,name,email,role:'student',points:0,completedLessons:[],completedTests:[],createdAt:serverTimestamp()})}catch(err){$('authMessage').textContent=ferr(err)}finally{$('registerButton')?.removeAttribute('disabled')}};
 $('forgotPassword').onclick=async()=>{const email=$('loginEmail').value.trim().toLowerCase();if(!email){$('authMessage').textContent='Önce e-posta adresini yaz.';return}try{await sendPasswordResetEmail(auth,email);$('authMessage').textContent='Şifre yenileme bağlantısı gönderildi.'}catch(err){$('authMessage').textContent=ferr(err)}};
}
function toggleType(inputId,buttonId){const i=$(inputId),b=$(buttonId);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Göster':'Gizle'}

onAuthStateChanged(auth,async user=>{try{if(!user){if(isStudent)hide($('studentApp'));if(!isStudent&&!isHome)location.href='./index.html';return}const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists()){await signOut(auth);return}const p=snap.data();if(isHome){location.href=p.role==='student'?'./student.html':'./teacher.html';return}if(isStudent&&p.role!=='student'){location.href='./teacher.html';return}if(isStudent)await initStudent(user,p)}catch(e){console.error(e);toast('Bağlantı sırasında bir hata oluştu.')}finally{hide($('loading'))}});

async function initStudent(user,p){show($('studentApp'));state.profile=p;const name=p.name||user.displayName||'Öğrenci';const initial=name[0].toUpperCase();$('sideName').textContent=name;$('topName').textContent=name;$('welcomeName').textContent=name.split(' ')[0];$('sideAvatar').textContent=initial;$('topAvatar').textContent=initial;$('profileAvatar').textContent=initial;$('profileName').textContent=name;$('profileEmail').textContent=user.email;
 $('logout').onclick=()=>signOut(auth);$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('backCourses').onclick=()=>studentView('courses');$('backTests').onclick=()=>studentView('tests');$('notifBtn').onclick=()=>{show($('notificationPanel'))};$('closeNotif').onclick=()=>hide($('notificationPanel'));$('closePdf').onclick=()=>hide($('pdfModal'));$('closeCourseModal').onclick=()=>hide($('courseModal'));
 document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>studentView(b.dataset.view,b));document.querySelectorAll('[data-viewgo]').forEach(b=>b.onclick=()=>studentView(b.dataset.viewgo));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTests(b.dataset.filter)});if($('courseSearch'))$('courseSearch').oninput=renderCourses;
 await loadStudentData();}
function studentView(view,btn){document.querySelectorAll('.student-page,.view').forEach(x=>x.classList.remove('active'));const target=view==='home'?'view-home':`view-${view}`;$(target)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');else document.querySelector(`.nav-btn[data-view="${view}"]`)?.classList.add('active');const names={home:'Ana Sayfa',courses:'Ders Merkezi','course-detail':'Ders',tests:'Test Merkezi',results:'Sonuçlarım',announcements:'Duyurular',profile:'Profilim',quiz:'Test'};$('pageTitle').textContent=names[view]||'Beray';$('sidebar').classList.remove('open')}

async function loadStudentData(){
 const uid=auth.currentUser.uid;
 const [courseSnap,lessonSnap,testSnap,resultSnap,annSnap]=await Promise.all([
  getDocs(query(collection(db,'courses'),orderBy('createdAt','desc'),limit(100))),
  getDocs(query(collection(db,'lessons'),limit(300))),
  getDocs(query(collection(db,'tests'),orderBy('createdAt','desc'),limit(100))),
  getDocs(query(collection(db,'results'),where('studentId','==',uid),limit(200))),
  getDocs(query(collection(db,'announcements'),orderBy('createdAt','desc'),limit(50)))
 ]);
 state.courses=courseSnap.docs.map(d=>({id:d.id,...d.data()})); state.courses=[...state.courses,...fallbackCourses.filter(s=>!state.courses.some(c=>c.id===s.id))];
 state.lessons=lessonSnap.docs.map(d=>({id:d.id,...d.data()}));
 state.tests=testSnap.docs.map(d=>({id:d.id,...d.data()}));
 state.results=resultSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));
 state.announcements=annSnap.docs.map(d=>({id:d.id,...d.data()}));
 updateDashboard();renderCourses();renderTests('all');renderResults();renderAnnouncements();updateNotifications();}

function updateDashboard(){const p=state.profile||{},lessons=(p.completedLessons||[]).length,tests=(p.completedTests||[]).length,scores=state.results.map(r=>Number(r.score||0)),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;$('statLessons').textContent=lessons;$('statTests').textContent=tests;$('statAverage').textContent=avg+'%';$('statPoints').textContent=p.points||0;$('profilePoints').textContent=p.points||0;$('profileLessons').textContent=lessons;$('profileTests').textContent=tests;}
function courseCard(c){const complete=(state.profile.completedLessons||[]).includes(c.id),lessonCount=c.sample?(c.lessons?.length||0):(state.lessons?.filter(l=>l.courseId===c.id).length||0);return `<article class="course-card ${c.color||''}"><div class="course-top"><span class="course-icon">${esc(c.icon||'▣')}</span><span class="course-status">${complete?'✓ Tamamlandı':'Yeni'}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.description||'')}</p><div class="course-meta"><span>📖 ${lessonCount||'Ders'}</span><span>${complete?'100%':'Başlangıç'}</span></div><div class="progress"><i style="width:${complete?100:18}%"></i></div><button class="ghost full-card" data-open-course="${c.id}">Dersi İncele →</button></article>`}
function renderCourses(){const search=($('courseSearch')?.value||'').toLowerCase();const data=state.courses.filter(c=>(c.title||'').toLowerCase().includes(search));$('courseGrid').innerHTML=data.map(courseCard).join('')||'<div class="empty">Ders bulunamadı.</div>';const featured=state.courses.filter(c=>c.featured).slice(0,3);$('homeCourses').innerHTML=featured.map(courseCard).join('');document.querySelectorAll('[data-open-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.openCourse));document.querySelectorAll('[data-open-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.openCourse));}
function openCourse(id){const c=state.courses.find(x=>x.id===id);if(!c)return;state.currentCourse=c;studentView('course-detail');const lessons=c.sample?(c.lessons||[]).map((x,i)=>({id:'s'+i,title:x[0],body:x[1],sample:true,courseId:id})):(state.lessons||[]).filter(l=>l.courseId===id);$('courseDetail').innerHTML=`<div class="detail-hero ${c.color||''}"><div><span class="kicker">DERS</span><h1>${esc(c.title)}</h1><p>${esc(c.description||'')}</p></div><div class="detail-icon">${esc(c.icon||'▣')}</div></div><div class="detail-body"><div><div class="section-head"><div><span class="kicker">MÜFREDAT</span><h2>Ders İçeriği</h2><p>${lessons.length||0} bölüm</p></div></div><div class="lesson-stack">${lessons.map((l,i)=>`<article class="lesson-row"><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(l.title)}</h3><p>${esc(l.body||'Konuyu aç ve çalışmaya başla.')}</p></div><button class="ghost" data-lesson-id="${esc(l.id)}">${l.videoUrl?'▶ Video':l.fileUrl?'📄 PDF':'İncele →'}</button></article>`).join('')||'<div class="empty">Bu ders için henüz konu eklenmemiş.</div>'}</div></div><aside class="detail-aside panel"><span class="kicker">İLERLEME</span><div class="big-progress">${(state.profile.completedLessons||[]).includes(c.id)?100:18}%</div><p>Dersi tamamladığında +10 puan kazanırsın.</p><button class="primary full" id="completeCourseBtn">${(state.profile.completedLessons||[]).includes(c.id)?'Tamamlandı ✓':'Dersi Tamamla'}</button></aside></div>`;const completeBtn=$('completeCourseBtn');if(completeBtn)completeBtn.onclick=()=>completeCourse(c.id);document.querySelectorAll('[data-lesson-id]').forEach(b=>b.onclick=()=>openLesson(c.id,b.dataset.lessonId));}
function openLesson(courseId,lessonId){const c=state.courses.find(x=>x.id===courseId);const l=c?.sample?(c.lessons||[])[Number(String(lessonId).slice(1))]:state.lessons.find(x=>x.id===lessonId);if(!l)return;if(l.fileUrl)openPDF(l.title,l.fileUrl);else if(l.videoUrl)window.open(l.videoUrl,'_blank','noopener');else {show($('courseModal'));$('modalCourseBody').innerHTML=`<span class="kicker">KONU</span><h2>${esc(l.title)}</h2><p class="lesson-reading">${esc(l.body||'Bu konu için içerik yakında eklenecek.')}</p><button class="primary" id="modalComplete">Konuyu okudum ✓</button>`;$('modalComplete').onclick=()=>{hide($('courseModal'));toast('Konu tamamlandı.');}}}
function openPDF(title,url){$('pdfTitle').textContent=title;$('pdfFrame').src=url;$('pdfOpen').href=url;show($('pdfModal'));}
async function completeCourse(id){if((state.profile.completedLessons||[]).includes(id)){toast('Bu ders zaten tamamlandı.');return}const ref=doc(db,'users',auth.currentUser.uid),snap=await getDoc(ref),p=snap.data(),list=[...(p.completedLessons||[])];list.push(id);await updateDoc(ref,{completedLessons:list,points:(p.points||0)+10});state.profile={...p,completedLessons:list,points:(p.points||0)+10};toast('Ders tamamlandı · +10 puan ⭐');updateDashboard();renderCourses();if(state.currentCourse?.id===id)openCourse(id);}

function testItem(t){const done=state.results.some(r=>r.testId===t.id),q=(t.questions||[]).length;return `<article class="test-card"><div class="test-badge">☑</div><div class="test-main"><div class="test-title"><h3>${esc(t.title||'Test')}</h3>${done?'<span class="score-pill">Çözüldü</span>':''}</div><p>${esc(t.description||'Bilgini ölç ve sonucunu anında gör.')}</p><div class="test-meta"><span>${q} soru</span><span>•</span><span>${done?'Sonucu var':'Yeni'}</span></div></div><button class="primary" data-start-test="${t.id}">${done?'Tekrar Çöz':'Teste Başla'} →</button></article>`}
function renderTests(filter){let list=state.tests;if(filter==='new')list=list.filter(t=>!state.results.some(r=>r.testId===t.id));if(filter==='done')list=list.filter(t=>state.results.some(r=>r.testId===t.id));$('testList').innerHTML=list.map(testItem).join('')||'<div class="empty">Bu filtrede test yok.</div>';const home=state.tests.slice(0,2);$('homeTests').innerHTML=home.map(testItem).join('')||'<div class="empty">Henüz test yayınlanmadı.</div>';document.querySelectorAll('[data-start-test]').forEach(b=>b.onclick=()=>startQuiz(state.tests.find(t=>t.id===b.dataset.startTest)));}
function renderResults(){const r=state.results,s=r.map(x=>Number(x.score||0)),avg=s.length?Math.round(s.reduce((a,b)=>a+b,0)/s.length):0,best=s.length?Math.max(...s):0;$('resultAverage').textContent=avg+'%';$('resultBest').textContent=best+'%';$('resultCount').textContent=r.length;$('resultList').innerHTML=r.map(x=>`<article class="result-card"><div><div class="result-title">${esc(x.testTitle)}</div><p>${x.correct||0} doğru · ${x.wrong||0} yanlış</p></div><strong>${x.score||0}%</strong></article>`).join('')||'<div class="empty">Henüz sınav sonucu yok.</div>';}
function renderAnnouncements(){$('announcementList').innerHTML=state.announcements.map(a=>`<article class="announcement-card"><span>◉</span><div><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p></div></article>`).join('')||'<div class="empty">Henüz duyuru yok.</div>';}
function updateNotifications(){const n=state.announcements.length;[$('navBadge'),$('notifCount')].forEach(e=>{if(!e)return;e.textContent=n;e.classList.toggle('hidden',!n)});$('notifList').innerHTML=state.announcements.slice(0,8).map(a=>`<div class="notif-item"><strong>${esc(a.title)}</strong><p>${esc(a.body)}</p></div>`).join('')||'<div class="empty small">Bildirim yok.</div>';}

async function startQuiz(test){if(!test?.questions?.length){toast('Bu testte henüz soru yok.');return}studentView('quiz');let i=0,correct=0,locked=false;const render=()=>{locked=false;const q=test.questions[i],total=test.questions.length;$('quizBox').innerHTML=`<div class="quiz-head"><div><span class="kicker">TEST</span><h1>${esc(test.title)}</h1></div><strong>${i+1}/${total}</strong></div><div class="quiz-progress"><i style="width:${((i+1)/total)*100}%"></i></div><div class="quiz-question"><h2>${esc(q.question)}</h2><div class="answers">${(q.options||[]).map((o,n)=>`<button class="answer" data-a="${n}"><span>${String.fromCharCode(65+n)}</span>${esc(o)}</button>`).join('')}</div></div>`;document.querySelectorAll('[data-a]').forEach(btn=>btn.onclick=()=>{if(locked)return;locked=true;const picked=+btn.dataset.a,answer=+q.correctAnswer;document.querySelectorAll('[data-a]').forEach((b,n)=>{b.disabled=true;if(n===answer)b.classList.add('correct');if(n===picked&&n!==answer)b.classList.add('wrong')});if(picked===answer)correct++;const next=document.createElement('button');next.className='primary quiz-next';next.textContent=i===total-1?'Testi Bitir':'Sonraki Soru';next.onclick=()=>{i++;i<total?render():finish()};$('quizBox').appendChild(next)})};const finish=async()=>{const total=test.questions.length,score=Math.round(correct/total*100),wrong=total-correct;await addDoc(collection(db,'results'),{studentId:auth.currentUser.uid,studentName:auth.currentUser.displayName||'',testId:test.id,testTitle:test.title,correct,wrong,score,createdAt:serverTimestamp()});const ref=doc(db,'users',auth.currentUser.uid),s=await getDoc(ref),p=s.data(),done=[...(p.completedTests||[])];if(!done.includes(test.id))done.push(test.id);const points=(p.points||0)+(correct*5);await updateDoc(ref,{completedTests:done,points});state.profile={...p,completedTests:done,points};$('quizBox').innerHTML=`<div class="quiz-result"><div class="result-symbol">${score>=80?'🏆':score>=50?'⭐':'📚'}</div><span class="kicker">TAMAMLANDI</span><h1>${score}%</h1><p>${correct}/${total} doğru cevap · +${correct*5} puan</p><button id="quizDone" class="primary">Sonuçları Gör →</button></div>`;await loadStudentData();$('quizDone').onclick=()=>studentView('results')};render()}

